// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using strawhats_api.Models;

namespace strawhatsapi.Migrations
{
    [DbContext(typeof(PirateDbContext))]
    [Migration("20180726092650_PirateCrewAddition")]
    partial class PirateCrewAddition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("strawhats_api.Models.Pirate", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Bounty");

                    b.Property<string>("CrewName");

                    b.Property<string>("Name");

                    b.Property<string>("NickName");

                    b.Property<string>("Position");

                    b.HasKey("ID");

                    b.ToTable("Pirates");
                });

            modelBuilder.Entity("strawhats_api.Models.PirateCrew", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("PirateCrews");
                });
#pragma warning restore 612, 618
        }
    }
}
