// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using strawhats_api.Models;

namespace strawhatsapi.Migrations
{
    [DbContext(typeof(PirateDbContext))]
    [Migration("20180727095923_AddedForeignKeyRefs")]
    partial class AddedForeignKeyRefs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("strawhats_api.Models.Pirate", b =>
                {
                    b.Property<int>("PirateID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Bounty");

                    b.Property<string>("Name");

                    b.Property<string>("NickName");

                    b.Property<int>("PirateCrewID");

                    b.Property<string>("Position");

                    b.HasKey("PirateID");

                    b.HasIndex("PirateCrewID");

                    b.ToTable("Pirates");
                });

            modelBuilder.Entity("strawhats_api.Models.PirateCrew", b =>
                {
                    b.Property<int>("PirateCrewID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("PirateCrewID");

                    b.ToTable("PirateCrews");
                });

            modelBuilder.Entity("strawhats_api.Models.Pirate", b =>
                {
                    b.HasOne("strawhats_api.Models.PirateCrew", "PirateCrew")
                        .WithMany("Pirates")
                        .HasForeignKey("PirateCrewID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
